# **XSPL Research Experience for High school students (REH)** 

written by Jackie Champagne (UT Austin), adapted by Hannah Hasson (U of Rochester)   

# Introduction to Python Day 1:
## Basic Syntax, Variables & Arrays

Hi there! Welcome to our brief introductory Python course for scientific coding. We will be teaching you skills ranging from the most basic tasks to some more advanced plotting techniques that will be helpful to you in research. 

These Colab notebooks work the same as **Jupyter notebooks**, which is a code editor you can use offline. The whole notebook is automatically saved periodically, but you can also save the outputs from your code as text files, plots, or images separate from the notebook. It is a great tool when you are building code from scratch and want to troubleshoot it or make a quick plot. \\

If you are attending this workshop live, the Questions in this notebook are meant to be a short few lines of code which you will do during the workshop. The Exercises, in a separate notebook, are longer problems you will work on after lecture, with the expectation of having all exercises finished and submitted by the end of the course. You are encouraged to work collaboratively.
 
Let's get started!

&nbsp; 

## **Importing packages**

The first thing you'll need to do when writing any code is import the packages you expect to use. **Packages** are groups of functions and keywords for some purpose. For example, the **numpy** package has mathematical functions like $sin(x)$ and constants like $\pi$.


You can put your **import statement** anywhere in your code, as long as it's written before you call a function from the package. But it's cleaner to put them all at the top, so that's what we'll do.

For this tutorial, let's load up numpy and a couple other useful examples. **To run the code in a cell, click on the cell and press SHIFT+ENTER or click the play button.** To *comment* your code, put a hashtag (#) in front of each line of your comment. Do this to add notes explaining your code.

&nbsp;

Some examples of imports and commenting:

In [ ]:
import numpy as np #'import' loads up the package. 

#you can use 'as' to define a shortcut so you don't need to type
#numpy before every use of the package. Most people use 'np'.

import matplotlib.pyplot as plt

from scipy import integrate #'from' allows you to import a specific sub-package

Now we don't have to import these packages again for the rest of our notebook! Calling a function or constant from one of your imported packages is simple. 

function:

    nameofpackage.somefunction()
or 

constant:

    nameofpackage.someconstant

Execute the example below to call the constant pi

In [ ]:
np.pi #remember we renamed numpy as np

3.141592653589793

If you try to use something from a package without importing it, you will get a sassy little error message

In [ ]:
pandas.read_csv("some_filename.pdf")

NameError: ignored

## **Setting Variables**

To define a variable, use =. 

The variable gets assigned the value of whatever you put to the right of the equal sign. This can be a number, text, or many other data types.

In [ ]:
a = 1
b = 2

Now Python will always know that a is 1 in this notebook. Setting variables is useful for things like constants, such as c = 3.0e8. Note that you can't start a variable name with a number!

&nbsp;

To check that this worked, we can print it out. The syntax for printing something is print(thing_you_want_to_print).

In [ ]:
print(a) #this prints the value of a
print("a") #this prints the letter a

Every new print statement goes to a new line. If you want to print multiple things together on the same line, you can just separate them by a comma in your print function.

In [ ]:
print("a equals", a)

&nbsp;

### **Boolean logic: comparing variables**

The double equals sign, ==, represents **boolean logic**. This refers to comparing values and seeing a relationship is **true or false**. This will come in handy when you write code where your data must meet a certain criterion. 


In [ ]:
a == 1 #check if a is equal to 1

In [ ]:
a == 2 #check if a is equal to 2

Do NOT confuse the single equals = (assign variable) with the double == (check if T/F that something is equal).

&nbsp; 

We can create criteria with multiple booleans!


---



OR statements: statement is TRUE if **either** A or B are true (or if both are true); statement is FALSE if both statements A and B are false.

AND statements: statement is TRUE if and only if **both** A and B are true; statement is FALSE if one or both is false.

&nbsp;

In Python, the phrase "a == 1 or 2" does not make sense. The full statement must be "a == 1 or a == 2" so that each piece of logic is separate.

In [ ]:
a == 1 or a == 2 #True or False

In [ ]:
a == 1 and a == 2 #True and False

In [ ]:
a == 1 or b == 2 #True or True

There are also other comparison operators. Here are all the basic ones you will use:
    
    ==   equal to
    !=   not equal to
    <    less than
    <=   less than or equal to
    >    greater than
    >=   greater than or equal to



## **Variable types**

There are 3 kinds of basic variables in Python: **strings, floats, and integers**. 

A floating point value (**float**) is a number followed by a decimal. An **integer** is a whole number. A **string** has quotes around it and is treated as a word rather than a numeric value.


### Question 1: What kinds of variables are the following? Fill it in as a comment on each line.

In [ ]:
i = 1 # int
j = 2.43 #float
k = 'Hello world!' #string
L = 3. #float
m = "123456" #string

Notice that this next line gives you an error. Why?

In [ ]:
n = Hello world!



You can **convert between variable types** if necessary, using the following commands:

    int()
    float()
    str()
    


int() will print the whole number value of the float and *does not round*. float() will follow an integer with a .0, which sounds pointless but is sometimes necessary for Python arithmetic. str() will put quotes around it so that Python reads it literally rather than numerically.



### Question 2: Convert i to a float and to a string. Convert j into an integer. Print type(k) to check your answer.


In [ ]:
# solution here

i_float = float(i)
i_string = str(i)
j_int = int(j)
print(i_float, i_string, j_int)
print(type(i_float), type(i_string), type(j_int))
print(type(k))

### Now convert k to an integer. What happens? 

In [ ]:
#solution here

k_int = int(k)

&nbsp;

## **Python arithmetic**

The syntax for doing arithmetic is the following:

    +           add
    -           subtract
    *           multiply
    /           divide
    **          power
    np.log()    log-base e (natural log)
    np.log10()  log-base 10
    np.exp()    exponential

In [ ]:
example = 5 + 3
print(example)

8


In [ ]:
i + j

3.43

In [ ]:
i * j

2.43

In [ ]:
j - i

1.4300000000000002

In [ ]:
i / j 

0.4115226337448559

&nbsp;
## **Arrays and Lists**

When working with data, you usually won't be dealing with just one number, but a collection of values. These collections can consist of floats, integers, strings, or a combination of them. We distinguish here two types of data structures: **lists** and **arrays**. 


A list is denoted by brackets: [ ], while an array must be defined with np.array(). 


We talk about the size of 2D arrays in terms of their **dimensions**: (rows, columns). You will later reference a specific element in an array by its (row, column) coordinate in the array. This is called **indexing**.


The following is a 1D list:

In [ ]:
beemovie = ['Barry B. Benson', 'Vanessa Bloome', 'Ray Liotta as Ray Liotta']
print(beemovie)

['Barry B. Benson', 'Vanessa Bloome', 'Ray Liotta as Ray Liotta']



For strings, this is fine, but **you will need to use *arrays* in order to manipulate them mathematically**. The array function is built into numpy. Here are a 1D array and a 2D array:

In [ ]:
myarray = np.array([1, 2, 3]) #1D
my2darray = np.array([[1, 2], [1, 2]]) #2D

Recall that in the beginning we imported numpy as np, so when we call functions from numpy we write np.function().

Notice the array function has parentheses (), and then the whole array must be enclosed in a set of brackets [] inside that. Within that, each row of the array should be in its own set of brackets, separated by commas.


### Question 3: Create the following 2D array and then print it:

    1 2 3
    4 5 6

In [ ]:
#solution here

another_2d_array = np.array([[1, 2, 3], [4, 5, 6]])

print(another_2d_array)

[[1 2 3]
 [4 5 6]]


&nbsp; 

## **Populating Arrays**

You don't always have to put values into your array manually, especially if, for example, you want a function to sample numbers evenly along some axis. 


Here are two ways to make arrays of evenly spaced numbers:

---


The first is np.linspace(), giving you an array with numbers between two values that are linearly spaced (e.g. 2, 4, 6, 8, 10). 

The second is np.logspace(), giving you an array between two values that are spaced evenly in log10 (e.g. 10^1, 10^1.1, 10^1.2).

&nbsp;
    
The syntax is the following:

    np.linspace(beginning number, end number, number of points)
    np.logspace(beginning exponent, end exponent, number of points)

&nbsp;

The following also works if you don't feel like calculating the exponent for np.log10

    np.logspace(np.log10(beginning number), np.log10(end number), number of points)
  
&nbsp;

These are *inclusive* sampling functions, meaning that the end number you give is included in the output array.



### Question 4: Create two arrays and assign them to variables. Each should have ten entries between 1 and 100, one in linear space and the other in logspace. Print them to check :)



In [ ]:
# solution here

linarray = np.linspace(1, 100, 10)
logarray = np.logspace(0, 2, 10)
logarray_alt = np.logspace(np.log10(1), np.log10(100), 10) #also correct

print(linarray, logarray, logarray_alt)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.] [  1.           1.66810054   2.7825594    4.64158883   7.74263683
  12.91549665  21.5443469   35.93813664  59.94842503 100.        ] [  1.           1.66810054   2.7825594    4.64158883   7.74263683
  12.91549665  21.5443469   35.93813664  59.94842503 100.        ]




Another quick way to create an array is through np.zeros. This populates an array with, well, zeros. It might sound useless at first, but it's an easy way to make an array that you will later replace with different values. It helps keep arrays at a fixed length, for instance. More on that later.

&nbsp;

The syntax is simply number of rows, number of columns. If it's 1D, then it can just be:

    np.zeros(3) #1x3 array of zeros
    
If it's larger than 1D, you need two sets of parentheses:

    np.zeros((rows, columns))
    

    
### Question 5: Create a 3x3 array of zeros (and print it out)

In [ ]:
#solution here

zeros_array = np.zeros((3, 3))

print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


&nbsp; 
&nbsp; 
-------
#PAUSE HERE AND TAKE A BREAK!
-------

&nbsp; 

## **Indexing**

An index is the position of some element in an array. Remember above we talked about using the coordinates (row, column) of an element in an array to get its value? 

### Note that **Python uses zero-based indexing!!**

This means that the first value of an array is the 0th index. Repeating that: **the first value in an array is the zeroth index**. So the second element has index 1, the third has index 2, and so on...

&nbsp;

To call a certain value from an array, call the array name followed by brackets containing the index of the value you want:

    array[0]

or for 2D

    array[0,0] # again in row, col notation
    
The value inside the brackets can also be a variable, so long as the variable is an **integer**. 

&nbsp;

A helpful shortcut is that you can also count backwards in your array with a negative sign, so **the last value in your array is always array[-1]**.


### Question 6: Print out the first and last value in your linspace array.

In [ ]:
#solution here

first_value = linarray[0]
last_value = linarray[-1]
print(first_value, last_value)

1.0 100.0


&nbsp; 
### **Slicing arrays**

Finally, you can also grab **slices** of arrays between certain index values. This is helpful if you want to plot only a small subsample of your data, for example.

&nbsp;

For slicing, use a colon. Syntax:

    :x - from beginning to index x
    x: - from index x until the end
    a:b - from index a to b
    a:b:c - every c'th entry between indices a and b
    
These can be combined, e.g. a::c goes from index a until the end in steps of c.

&nbsp;

Slicing is *exclusive*, so the last index of a range isn't included. For example, if you want to take index two through six of an array you should do:

    array[2:7]


### Question 7: Print out the following: a) your linear array until index 5; b) your log array beginning at index 1; c) your linear array between indices 4 and 8; and d) your full linear array in steps of 2 indices.

In [ ]:
#solution here

until_index_5 = linarray[:6]
begin_at_1 = logarray[1:]
between_4_8 = linarray[4:9]
steps_of_2 = linarray[::2]
steps_of_2_longway = linarray[0:-1:2] #this is also correct
print(until_index_5, begin_at_1, between_4_8, steps_of_2, steps_of_2_longway)

[ 1. 12. 23. 34. 45. 56.] [  1.66810054   2.7825594    4.64158883   7.74263683  12.91549665
  21.5443469   35.93813664  59.94842503 100.        ] [45. 56. 67. 78. 89.] [ 1. 23. 45. 67. 89.] [ 1. 23. 45. 67. 89.]


&nbsp; 

## **Array Manipulation and Attributes**

You can manipulate all elements of an array with one statement. Check it out:

### Question 8: Create a new array which is your logspace array divided by 2. Create another new array which is your linspace array + 2.

In [33]:
#solution here

logarray_div_2 = logarray / 2
linarray_plus_2 = linarray + 2

print(logarray_div_2, linarray_plus_2)

[ 0.5         0.83405027  1.3912797   2.32079442  3.87131841  6.45774833
 10.77217345 17.96906832 29.97421252 50.        ] [  3.  14.  25.  36.  47.  58.  69.  80.  91. 102.]




You can **add values to the end of an array** using np.append(). Use it like this:

    np.append(array, something_appended)
    
You can even append another array, like this:

    np.append(array, [5, 6])
    np.append(array1, array2)


    
### Question 9: Create a new array which is another linear array from 100 to 200 appended to your linspace array.

In [34]:
#solution here

linarray_append = np.append(linarray, np.linspace(100, 200, 10))
print(linarray_append)

[  1.          12.          23.          34.          45.
  56.          67.          78.          89.         100.
 100.         111.11111111 122.22222222 133.33333333 144.44444444
 155.55555556 166.66666667 177.77777778 188.88888889 200.        ]




The last part of today will be showing you how to acquire different information from an array. Some of these are attributes of the array, and some of them are attributes of np itself, so you may need to look this up again in the future.


Attributes of the array means that you call this by nameofarray.command:
   
    ndim - prints dimensions of your array
    size - number of elements in n-dimensional array
    shape - shape given by (rows, columns)
    flatten() - collapses the array along one axis
    T - transpose the matrix
    reshape(x, y) - change the dimensions of the array to x, y -- the total number of elements (x*y) MUST match
   
Attributes of numpy, meaning that you call it by np.command(nameofarray):

    sum - sum all the elements in the array
    min - print minimum value in array
    max - print maximum value
    sort - print array in ascending order
    len - print number of elements along the row axis
    dot - matrix multiplication


### Question 10: Find the shape of your last array, and then print the sum of that array
    

In [35]:
#solution here

linarray_append.shape
print(np.sum(linarray_append))

2005.0


&nbsp; 

### You will have received a link to exercises to do at the end of each day's lesson (Exercises.ipynb). Please do the Day 1 exercises with your fellow students before the start of the next session!